### ISSUE TITLE
Cannot load plugins\Capatchafy\config.yml

### ISSUE THREAD

**Issue by mgflames** [Hockeyfan360/Capatchafy#10]
I can't load Capatchafy, I get this error:

01.08 17:37:38 [Server] INFO [Capatchafy] Enabling Capatchafy v1.0
01.08 17:37:38 [Server] ERROR Cannot load plugins\Capatchafy\config.yml
01.08 17:37:38 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
01.08 17:37:38 [Server] INFO in 'string', line 32, column 1:
01.08 17:37:38 [Server] INFO recapatcha-key:6LerUysUAAAAAPKAN ... 
01.08 17:37:38 [Server] INFO ^
01.08 17:37:38 [Server] INFO could not find expected ':'
01.08 17:37:38 [Server] INFO in 'string', line 33, column 1:
01.08 17:37:38 [Server] INFO recapatcha-secret:6LerUysUAAAAAO ... 
01.08 17:37:38 [Server] INFO ^
01.08 17:37:38 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
01.08 17:37:38 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
01.08 17:37:38 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.12.jar:git-Spigot-596221b-2c5c611]
01.08 17:37:38 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.12.jar:git-Spigot-596221b-2c5c611]
01.08 17:37:38 [Server] INFO at me.hockey.capatchafy.Configuration.loadConfigs(Configuration.java:85) [Capatchafy-1.0-jar-with-dependencies.jar:?]

Please help.

Thanks.

**Comment by mayokek** [comment]
You need add a space after `:` like `recapatcha-key: <key>` not `recapatcha-key:<key>`

**Comment by BlazingFlames** [comment]
I've fixed that, but now I get this error:

at org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:93) ~[?:?]
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:282) ~[?:?]
at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:269) ~[?:?]
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:334) ~[?:?]
at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:117) ~[?:?]
at me.hockey.capatchafy.httpd.HttpdServer.startServer(HttpdServer.java:37) ~[?:?]
at me.hockey.capatchafy.Capatchafy.onEnable(Capatchafy.java:72) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

P.S. this is me on my other account. @InfamousYT

**Comment by mayokek** [comment]
By the look of it, it failed to run a server. Did you set it up?

**Comment by BlazingFlames** [comment]
I've fixed it - but now when I turn it on, it says for me to go to null in my browser.

This is my config:

`#This is the main configuration file for Capatchafy 1.0, a plugin by James Depp.
#Authorized-IPs are located in ips.yml. If you want to wipe them, delete ips.yml, WHILE THE SERVER IS STOPPED. It will reverse your actions if the server is alive.

#If you would like Capatchafy to be enabled all the time, you can specify that here.
always-on: false

#This is the default security level. This value should be an integer between 1 and 3.
#Any security level can be selected with the /capatchafy command.
#1 - Friendly. One time verification, ips will be stored in config.
#2 - Moderate (Recommended). You must verify each time the server restarts/reloads.
#3 - Strict. You must verify each time you join.
security-level: 2

#Hostname - The ip that you want Capatchafy to listen on goes here.
#You don't HAVE to change this, but leaving it will cause problems when a player tries to find the link to the capatcha.
hostname: 92.222.167.249

#Port - The port that you want Capatchafy to run on goes here.
#Use port 80 if you don't want your players to have to type a port in the address bar. On some machines, port 80 may already be in use.
#If you're not sure about which port to use, just pick a random one. If you're running a VPS, be sure to open the port in the firewall.
port: 999

#Whitelisted IPs - IPs that will never have to go through the capatcha verification process.
whitelisted-ips:
  - 127.0.0.1

#This is the tricky part. You will need to obtain api keys for reCapatcha.

#To obtain a reCapatcha key, click on https://www.google.com/recaptcha/intro/index.html and click "Get Started."
#Enter in a name for your 'site', it can be anything. Then, give the hostname you put here as the url to your capatcha.
#Your site key goes in the 'recapatcha-key' section, your secret key (which you should never give out) goes in the 'recapatcha-secret' section.
recapatcha-key: ******
recapatcha-secret: ******`

**Comment by mayokek** [comment]
Is it enabled? `always-on: off`, I believe it is not enabled.

**Comment by BlazingFlames** [comment]
I use /capatchafy on

**Comment by Hockeyfan360** [comment]
@BlazingFlames The HttpServer is not initializing correctly. The most common cause of this problem is a Caoatchafy being unable to bind to a port. Make sure the hostname is also correct, too. The port needs to be open on the machine.

**Comment by Hockeyfan360** [comment]
Closed due to inactivity.
